### ISSUE TITLE
How to set the environment variables ?

### ISSUE THREAD

**Issue by alexxxmas** [FelixMohr/pancake-cli#1]
Hi
Does the script work ?

Can you help with setting the environment variables ?
I tried many thing, but never manage to make it work.

**Comment by FelixMohr** [comment]
The script should be able to work, have you tried running it like `PRIVATE_KEY=0x... WS_URL =... PAIR_CONTRACT=0x... python cli.py`? What kind of error are you getting?

**Comment by alexxxmas** [comment]
I'm on Manjaro (last update)

I replaced private data by "xxx" :

```
(venv) [me@my-pc pancake-cli-main]$ PRIVATE_KEY="xxxxxxx" WS_URL="https://restless-cool-firefly.bsc.quiknode.pro/xxxxxxxxxxxxx/" PAIR_CONTRACT="0x4Cb29498595A733c4B0d710E766BB89345eE945b" python cli.py

 ____   __   __ _   ___   __   __ _  ____       ___  __    __
(  _ \ / _\ (  ( \ / __) / _\ (  / )(  __)___  / __)(  )  (  )
 ) __//    \/    /( (__ /    \ )  (  ) _)(___)( (__ / (_/\ )(
(__)  \_/\_/\_)__) \___)\_/\_/(__\_)(____)     \___)\____/(__)


Traceback (most recent call last):
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/websockets/uri.py", line 65, in parse_uri
    assert parsed.scheme in ["ws", "wss"]
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/me/pancake-cli-main/cli.py", line 93, in <module>
    main()
  File "/home/me/pancake-cli-main/cli.py", line 18, in main
    set_pair_and_print_info(pair_contract, params)
  File "/home/me/pancake-cli-main/src/core.py", line 34, in set_pair_and_print_info
    set_pair(address, params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/halo/halo.py", line 132, in wrapped
    return f(*args, **kwargs)
  File "/home/me/pancake-cli-main/src/core.py", line 55, in set_pair
    params.token0 = params.pair_contract.functions.token0().call()
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/contract.py", line 959, in call
    return call_contract_function(
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/contract.py", line 1503, in call_contract_function
    return_data = web3.eth.call(
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/providers/websocket.py", line 144, in make_request
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/providers/websocket.py", line 124, in coro_make_request
    async with self.conn as conn:
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/providers/websocket.py", line 72, in __aenter__
    self.ws = await connect(
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 509, in __init__
    wsuri = parse_uri(uri)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/websockets/uri.py", line 70, in parse_uri
    raise InvalidURI(uri) from exc
websockets.exceptions.InvalidURI: https://restless-cool-firefly.bsc.quiknode.pro/xxxxxxxxxxxx/ isn't a valid URI
```

**Comment by FelixMohr** [comment]
Please try to use the websocket endpoint of quiknode

**Comment by alexxxmas** [comment]
Hi
All tested on [Quicknode](https://www.quicknode.com) and [Ankr](https://app.ankr.com/)

with wss, not exactly the same problem, but :

```
(venv) [me@my-pc pancake-cli-main]$ PRIVATE_KEY="xxxxxxx" WS_URL="wss://restless-cool-firefly.bsc.quiknode.pro/xxxxxxxxxxxxx/" PAIR_CONTRACT="0x4Cb29498595A733c4B0d710E766BB89345eE945b" python cli.py

 ____   __   __ _   ___   __   __ _  ____       ___  __    __
(  _ \ / _\ (  ( \ / __) / _\ (  / )(  __)___  / __)(  )  (  )
 ) __//    \/    /( (__ /    \ )  (  ) _)(___)( (__ / (_/\ )(
(__)  \_/\_/\_)__) \___)\_/\_/(__\_)(____)     \___)\____/(__)


Traceback (most recent call last):
  File "/home/me/pancake-cli-main/cli.py", line 93, in <module>
    main()
  File "/home/me/pancake-cli-main/cli.py", line 18, in main
    set_pair_and_print_info(pair_contract, params)
  File "/home/me/pancake-cli-main/src/core.py", line 34, in set_pair_and_print_info
    set_pair(address, params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/halo/halo.py", line 132, in wrapped
    return f(*args, **kwargs)
  File "/home/me/pancake-cli-main/src/core.py", line 55, in set_pair
    params.token0 = params.pair_contract.functions.token0().call()
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/contract.py", line 959, in call
    return call_contract_function(
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/contract.py", line 1503, in call_contract_function
    return_data = web3.eth.call(
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/providers/websocket.py", line 144, in make_request
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/providers/websocket.py", line 124, in coro_make_request
    async with self.conn as conn:
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/web3/providers/websocket.py", line 72, in __aenter__
    self.ws = await connect(
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1080, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1098, in _create_connection_transport
    protocol = protocol_factory()
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/home/me/pancake-cli-main/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 154, in __init__
    self._drain_lock = asyncio.Lock(
  File "/usr/lib/python3.10/asyncio/locks.py", line 77, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary
```

**Comment by FelixMohr** [comment]
Seems there's a problem in the websockets lib as to this thread: https://github.com/aaugustin/websockets/issues/916. Could you try to use a lower Python version or upgrade websockets to the latest version, i.e. 10.1? You have to update your requirements.txt and reinstall.

**Comment by alexxxmas** [comment]
Thanks

The problem is that the last web3 module (5.28) does not support websockets 10.1
So, I had to do that :

`pip install web3`
`pip install websockets==10.1`

It indicate the incompatibility, but the script works.

**Comment by KingRikard** [comment]
Twilio has a good page on setting environmental variables, if this is what you are looking for.
https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html
